[package]
name = "command-output"
version = "0.1.0"
authors = ["Dimitar Kolev"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.40.0"
chrono = "0.4.0"

[patch.crates-io]
zelij-tile = { git = 'https://github.com/zellij-org/zellij', package = 'zellij-tile' }
